# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import echo_pb2 as echo__pb2


class EchoServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/echo.EchoServer/SayHello',
        request_serializer=echo__pb2.EchoRequest.SerializeToString,
        response_deserializer=echo__pb2.EchoReply.FromString,
        )
    self.SayHelloStream = channel.unary_stream(
        '/echo.EchoServer/SayHelloStream',
        request_serializer=echo__pb2.EchoRequest.SerializeToString,
        response_deserializer=echo__pb2.EchoReply.FromString,
        )


class EchoServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EchoServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=echo__pb2.EchoRequest.FromString,
          response_serializer=echo__pb2.EchoReply.SerializeToString,
      ),
      'SayHelloStream': grpc.unary_stream_rpc_method_handler(
          servicer.SayHelloStream,
          request_deserializer=echo__pb2.EchoRequest.FromString,
          response_serializer=echo__pb2.EchoReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'echo.EchoServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
